ekyna_agenda_category_admin_home:
    path: ""
    defaults: { _controller: "ekyna_agenda.category.controller:homeAction" }
    requirements:
        _method: GET

ekyna_agenda_category_admin_list:
    path: /list
    defaults: { _controller: "ekyna_agenda.category.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_agenda_category_admin_new:
    path: /new
    defaults: { _controller: "ekyna_agenda.category.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_agenda_category_admin_show:
    path: /{categoryId}/show
    defaults: { _controller: "ekyna_agenda.category.controller:showAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_agenda_category_admin_edit:
    path: /{categoryId}/edit
    defaults: { _controller: "ekyna_agenda.category.controller:editAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+

ekyna_agenda_category_admin_remove:
    path: /{categoryId}/remove
    defaults: { _controller: "ekyna_agenda.category.controller:removeAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+
