ekyna_agenda_example_index:
    path: ""
    defaults: { _controller: EkynaAgendaBundle:Example:index }
    methods: [GET]

ekyna_agenda_example_detail:
    path: /{slug}
    defaults: { _controller: EkynaAgendaBundle:Example:detail }
    methods: [GET]
    requirements:
        slug: "[a-zA-Z0-9-]+"
